version: '3'

tasks:
  update:
    cmds:
      - composer update

  test:
    desc: Test client code
    deps:
      - update
    cmds:
      - >
        docker run -d
        --name ledger-{{.RANDOM}}
        --rm
        -e NUMARY_SERVER_HTTP_BIND_ADDRESS=0.0.0.0:3068
        -p 3068:3068
        ghcr.io/numary/ledger:v1.0.0-rc3
      - defer: docker stop ledger-{{.RANDOM}}
      - ./vendor/bin/phpunit