version: '3'

tasks:
  update:
    cmds:
      - composer update

  test:
    desc: Test client code
    deps:
      - update
    cmds:
      - >
        docker run -d
        --name ledger
        --rm
        -e NUMARY_SERVER_HTTP_BIND_ADDRESS=0.0.0.0:3068
        -p 3068:3068
        ghcr.io/numary/ledger:latest
      - defer: docker stop ledger
      - ./vendor/bin/phpunit