<?php
/**
 * AccountsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Numary\Ledger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ledger API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.9.6
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Numary\Ledger\Test\Api;

use \Numary\Ledger\Configuration;
use \Numary\Ledger\ApiException;
use \Numary\Ledger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccountsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Numary\Ledger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addMetadataToAccount
     *
     * Add metadata to an account.
     *
     */
    public function testAddMetadataToAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countAccounts
     *
     * Count the accounts from a ledger.
     *
     */
    public function testCountAccounts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccount
     *
     * Get account by its address.
     *
     */
    public function testGetAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAccounts
     *
     * List accounts from a ledger.
     *
     */
    public function testListAccounts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
