<?php
/**
 * StatsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Numary\Ledger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ledger API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Numary\Ledger\Test\Api;

use Numary\Ledger\Api\StatsApi;
use \Numary\Ledger\Configuration;
use \Numary\Ledger\ApiException;
use \Numary\Ledger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Numary\Ledger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatsApiTest extends ApiTest
{

    /**
     * Setup before running each test case
     * @throws \Exception
     */
    public function setUp(): void
    {
        parent::setUp();
        $this->statsApi = new StatsApi($this->httpClient, $this->config);
    }

    /**
     * Test case for readStats
     *
     * Get Stats.
     *
     * @throws ApiException
     */
    public function testReadStats()
    {
        $stats = $this->statsApi->readStats($this->ledger);
        $this->assertEquals(0, $stats->getData()->getAccounts());
        $this->assertEquals(0, $stats->getData()->getTransactions());
    }
}
